/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_jnithread_ndk_PthreadUtil */

#ifndef _Included_com_aispeech_jnithread_ndk_PthreadUtil
#define _Included_com_aispeech_jnithread_ndk_PthreadUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_jnithread_ndk_PthreadUtil
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
extern "C"
JNIEXPORT jstring JNICALL Java_com_aispeech_jnithread_ndk_PthreadUtil_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_aispeech_jnithread_ndk_PthreadUtil
 * Method:    normalThread
 * Signature: ()V
 */
extern "C"
JNIEXPORT void JNICALL Java_com_aispeech_jnithread_ndk_PthreadUtil_normalThread
  (JNIEnv *, jobject);

/*
 * Class:     com_aispeech_jnithread_ndk_PthreadUtil
 * Method:    mutexThread
 * Signature: ()V
 */
extern "C"
JNIEXPORT void JNICALL Java_com_aispeech_jnithread_ndk_PthreadUtil_mutexThread
  (JNIEnv *, jobject);

/*
 * Class:     com_aispeech_jnithread_ndk_PthreadUtil
 * Method:    callbackFromC
 * Signature: ()V
 */
extern "C"
JNIEXPORT void JNICALL Java_com_aispeech_jnithread_ndk_PthreadUtil_callbackFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_aispeech_jnithread_ndk_PthreadUtil
 * Method:    subCalbackThread
 * Signature: ()V
 */
extern "C"
JNIEXPORT void JNICALL Java_com_aispeech_jnithread_ndk_PthreadUtil_subCalbackThread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
