/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_jnithread_ndk_ParcelUtil */

#ifndef _Included_com_aispeech_jnithread_ndk_ParcelUtil
#define _Included_com_aispeech_jnithread_ndk_ParcelUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_jnithread_ndk_ParcelUtil
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_aispeech_jnithread_ndk_ParcelUtil_nativeCreate
  (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_aispeech_jnithread_ndk_ParcelUtil_nativeDestory
        (JNIEnv *, jobject,jlong);


/*
 * Class:     com_aispeech_jnithread_ndk_ParcelUtil
 * Method:    nativeWriteInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_aispeech_jnithread_ndk_ParcelUtil_nativeWriteInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_aispeech_jnithread_ndk_ParcelUtil
 * Method:    nativeReadInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_aispeech_jnithread_ndk_ParcelUtil_nativeReadInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aispeech_jnithread_ndk_ParcelUtil
 * Method:    nativeSetDataPosition
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_aispeech_jnithread_ndk_ParcelUtil_nativeSetDataPosition
  (JNIEnv *, jobject, jlong,jint);


JNIEXPORT void JNICALL Java_com_aispeech_jnithread_ndk_ParcelUtil_nativeWriteString
        (JNIEnv *, jobject, jlong, jstring);

JNIEXPORT jstring JNICALL Java_com_aispeech_jnithread_ndk_ParcelUtil_nativeReadString
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
